### ISSUE TITLE
下载后编译提示没有stm32_rom.sct文件

### ISSUE THREAD

**Issue by wangxiufeng1104** [iamluoyijie/funny_car#1]
**.\build\rtthread-stm32f4xx.axf: error: L6031U: Could not open scatter description file .\stm32_rom.sct: No such file or directory**

**Comment by yijieluo** [comment]
上传的时候把一些配置文件删了，我本地编译没问题，我明天上午看一下

**Comment by yijieluo** [comment]
已经改好了，你可以试一下

**Comment by wangxiufeng1104** [comment]
编译通过了
